service: aws-nodejs-boilerplate

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  #region: us-east-1
  versionFunctions: false
functions:
  hello:
    handler: src/handler.hello
